export const newArrivals = [
  {
    id: 1,
    name: "T-shirt with Tape Details",
    image: "/public/images/image 7.png",
    price: 120,
    oldPrice: null,
    rating: 4.5,
    discount: null,
  },
  {
    id: 2,
    name: "Skinny Fit Jeans",
    image: "/public/images/image 8.png",
    price: 240,
    oldPrice: 260,
    rating: 3.5,
    discount: "-20%",
  },
  {
    id: 3,
    name: "Checkered Shirt",
    image: "/public/images/image 9.png",
    price: 180,
    oldPrice: null,
    rating: 4.5,
    discount: null,
  },
  {
    id: 4,
    name: "Sleeve Striped T-shirt",
    image: "/public/images/image 10.png",
    price: 130,
    oldPrice: 160,
    rating: 4.5,
    discount: "-30%",
  },
];

export const topSelling = [
  {
    id: 5,
    name: "Vertical Striped Shirt",
    image: "/public/images/image 11.png",
    price: 212,
    oldPrice: 232,
    rating: 5,
    discount: "-20%",
  },
  {
    id: 6,
    name: "Courage Graphic T-shirt",
    image: "/public/images/image 12.png",
    price: 145,
    oldPrice: null,
    rating: 4,
    discount: null,
  },
  {
    id: 7,
    name: "Loose Fit Bermuda Shorts",
    image: "/public/images/image 13.png",
    price: 80,
    oldPrice: null,
    rating: 3,
    discount: null,
  },
  {
    id: 8,
    name: "Faded Skinny Jeans",
    image: "/public/images/image 14.png",
    price: 210,
    oldPrice: null,
    rating: 4.5,
    discount: null,
  },
];